### ISSUE TITLE
Service port forward support

### ISSUE THREAD

**Issue by KevinDenys** [harbur/kubernetic#102]
Hi,

Any idea of service port forwarding will be supported in the future?

**Comment by inikolaev** [comment]
Just found this Kube Forwarder: https://electronjs.org/apps/kube-forwarder
Would be nice to implement something similar here as well.

**Comment by spyro2000** [comment]
Yes, second that

**Comment by dkapanidis** [comment]
The feature will be included in next milestone.

**Comment by dkapanidis** [comment]
Added support for port forwarding (2.6.0)

All pods that have port definitions can now be port-forwarded locally to a random free port, a URL is provided which is opened on the default browser of your OS.

A global section of port forwards is also added so that you can view/stop opened port-forwards.

![2020-04-13 17-35-11 2020-04-13 17_39_23](https://user-images.githubusercontent.com/367397/79134290-bf44e900-7dad-11ea-9fc3-26dbda440d4e.gif)

currently the port-forwarding is done on Pod level, in next releases it will be provided in controllers and services.

**Comment by spyro2000** [comment]
This is cool! But It's lacking two important features to be actually useful for me:

- Not possible to set the local port (same / manual). For example: 8080 -> 8080 or 8080 -> 1234
- Not possible to manually specifiy source port (for some reason, port 5005 for remote debugging doesn't show up while it is indeed working with kubectl via _kubectl -n std port-forward my-pod-name 5005_
