### ISSUE TITLE
[WINDOWS] Can't set properly kubeconfig file

### ISSUE THREAD

**Issue by batreseau** [harbur/kubernetic#110]
Hello all,

I have many Kubernetes cluster and i want to see if i can monitor them using Kubernetics.
I tried to find a way to fill my config file with all clusters but when i start Kubernetic, there is no datas.

I created a kube folder within a config file filled from config file of my cluster
In powershell i created env variable with:

$env:KUBECONFIG="C:\Users\your_user_name\.kube\config"

If anyone can help me ;)

**Comment by grzesuav** [comment]
https://github.com/harbur/kubernetic/issues/28

**Comment by grzesuav** [comment]
kubernetic has fixed kube config loction, it does not use env variable

**Comment by batreseau** [comment]
Thanks for your quick Reply. I checked #28 post but can find anything related to kube config path in Windows. So i think i missed to say all my cluster running Ubuntu 18.04 and no kubernetes agent running on my windows system. Just wanna use kubernetic from windows to monitor linux clusters.

**Comment by otomazeli** [comment]
your are missing something
$env:KUBECONFIG="C:\Users\your_user_name.kube\config"
$env:KUBECONFIG="C:\Users\your_user_name\.kube\config"  <- before .kube you have a \

**Comment by dkapanidis** [comment]
On v2.5.0 version the KUBECONFIG can now be configured in Preferences section:

<img width="1107" alt="Screenshot 2020-03-02 at 21 44 05" src="https://user-images.githubusercontent.com/367397/75716216-09c34800-5ccf-11ea-9569-855342079273.png">

It supports multiple files, same way `kubectl` uses KUBECONFIG environment variable.

Also extra PATH can be defined in order to locate external auth binaries that may be referenced in your KUBECONFIG files.
