### ISSUE TITLE
[Feature request] Give feedback if the connection is established between app & cluster

### ISSUE THREAD

**Issue by Wesseldr** [harbur/kubernetic#130]
OsX: 10.14.6
App: 2.4.3

**Current behaviour**
Whenever the connection to the k8s cluster is established or not, it is not clear if there is any connection. Every item selected just shows up empty, so it could be empty or i've lost connection.
I like the fact that it is not making any annoying popups about it though so please keep that :-) 

**Requested behaviour**
Make a very subtle led on the status bar if the connection is:
- No connection (red solid) / There is a connection but authentication fails (red blinking)
- Connecting (orange) Waiting for authentication but there is a server connection
- Connected (green) Connected and authenticated.

For example:
![suggestion](https://user-images.githubusercontent.com/4012809/73352202-ec92f800-4290-11ea-9ca4-86a46a6a7a35.png)

Thank you for the good work so far!

Wessel

**Comment by dkapanidis** [comment]
Thanks for the feedback!

This is now fixed in latest release (v2.5.0)

Now There is a server icon near the context dropdown that displays the current state of connectivity.

Pending to connect:
<img width="422" alt="Screenshot 2020-02-22 at 12 18 15" src="https://user-images.githubusercontent.com/367397/75091447-9fdbcd80-556d-11ea-96de-99c52bf10777.png">

Connected:
<img width="416" alt="Screenshot 2020-02-22 at 12 15 28" src="https://user-images.githubusercontent.com/367397/75091403-0b716b00-556d-11ea-9bc6-b9cbb3aa7e0b.png">

Disconnected:
<img width="414" alt="Screenshot 2020-02-22 at 12 16 58" src="https://user-images.githubusercontent.com/367397/75091441-9bafb000-556d-11ea-991a-489ce6a35bca.png">

**Comment by Wesseldr** [comment]
I saw it. Very well done !!! Thank you 🙏

Verstuurd vanaf mijn iPhone
