### ISSUE TITLE
Network connection seems broken after standby

### ISSUE THREAD

**Issue by spyro2000** [harbur/kubernetic#151]
After resuming from standby, I have to manually restart Kubernetic. Otherwise it will not display current results:

![image](https://user-images.githubusercontent.com/8479925/80948967-663c0400-8df3-11ea-825b-7a548242d7ee.png)

**Comment by spyro2000** [comment]
(polite bump)

**Comment by dkapanidis** [comment]
This is now fixed on v2.9.0

websockets are now opened on each page separately scoped on the active resources instead of keeping a session-wide websocket. This fixes the dead websocket issue when connectivity is broken, simply refresh the page (by clicking on the title) or change page and it will load properly.
