### ISSUE TITLE
[New feature] View init-containers in pods

### ISSUE THREAD

**Issue by nikkoura** [harbur/kubernetic#153]
Pods' containers list does not currently include init containers. 
Their presence could be helpful; browsing their logs can be especially useful when they are failing.

**Comment by dkapanidis** [comment]
done on v2.8.0, pending next release:


![initcontainers](https://user-images.githubusercontent.com/367397/82363760-90eea500-9a0e-11ea-898c-b0a969677550.gif)

**Comment by dkapanidis** [comment]
Issue is related and can be used with #89 (show logs of previous run) in case init-container fails continuously.

[EphemeralContainers] are also added to be displayed in the logs, in the near future you'll be able to bring-your-own image in the Terminal tab for debugging purposes.

![ephemeralcontainers](https://user-images.githubusercontent.com/367397/82364770-027b2300-9a10-11ea-8e3f-5b53f9936f75.gif)

[EphemeralContainers]: https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container

Note that ephemeralContainers are alpha and in order to be enabled you need to activate the feature-gate EphemeralContainers. To do that in minikube:

```
minikube start --feature-gates=EphemeralContainers=true
```
