### ISSUE TITLE
[Feature request] Scaling terminal/items screen

### ISSUE THREAD

**Issue by alexremn** [harbur/kubernetic#155]
As a user, I would like to have a possibility to change size of terminal/items (ie pods) screens, cause on big screens there are a lot of blank unused space.

Thank you in advance!

**Comment by dkapanidis** [comment]
hi, can you share a screen of your unused blank space so that we can focus on that, screens should be responsive and take all space, aside from the ability to change font sizes.

**Comment by alexremn** [comment]
Hey, @dkapanidis 
Sure, here we go.

Pods:
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/14985732/82050659-30cfca00-96c1-11ea-957b-8f555220e754.png">

Terminal:
<img width="1622" alt="image" src="https://user-images.githubusercontent.com/14985732/82050699-45ac5d80-96c1-11ea-90cc-f15f7407f7c6.png">

**Comment by dkapanidis** [comment]
There are three separate issues, one per screenshot:
1) Pods pagination will be configurable, not solved yet, but the pagination is now at the bottom of the screen, instead of floating.

2) Fixed terminal sizing it now fits on the entire screen. Also background has been themed to fit the rest of the code sections grey coloring.

3) The terminal inside now fits the entire screen, but depending on the shell options, the shell prompt itself may be restricted. Some of the problems arise by changing shell inside the terminal, so there is now a dropdown option to choose your shell and avoid re-shelling (I just this word up, not sure if it is a thing)

![terminal](https://user-images.githubusercontent.com/367397/82440842-45370c80-9a9d-11ea-87c2-c4b54bcd043b.gif)

on the above example I open a terminal session on a Pod running `nginx` with `sh` shell. Other shell options include `bash`, `cmd`, `powershell`.

**Comment by alexremn** [comment]
@dkapanidis Thanks a lot. Saw it is planned in 2.8.0. Waiting impatiently.

**Comment by dkapanidis** [comment]
Pagination option added on the Preferences menu:

<img width="1095" alt="Screenshot 2020-05-21 at 08 58 15" src="https://user-images.githubusercontent.com/367397/82532265-44f04d00-9b41-11ea-8303-0637cb9ad6f1.png">
