### ISSUE TITLE
Unable to copy/paste into pod terminal

### ISSUE THREAD

**Issue by foal** [harbur/kubernetic#169]
Open terminal but unable to copy/paste content from it. Ctrl-C works a shell command, no context menu

**Comment by Sonorpearl** [comment]
Any updates on this? It would greatly improve the effectiveness of our work.

**Comment by dominch** [comment]
Yet again - #75 would solve this issue too. 
I noticed this problem and I think that everybody used to his own terminal and c&p keyboard combination. Right mouse click is best for me (like putty does) because I'm usually selecting something by mouse there, others would like something else and that should be setting of terminal.

**Comment by dkapanidis** [comment]
Fixed on `4.0.0`

Issue affected win and linux but not mac. Keyboard shortcuts already existed to the app for copy/paste (`ctrl+c` and `ctrl+v`) and you could use them in other areas (e.g. copy from view or edit screens) but they didn't work properly on Terminal.

This is due to `ctrl+c` being shadowed by the terminal shortcut for SIGINT signal.

To differentiate the two, the UI now checks if there is selected text on screen then `ctrl+c` is treated as copy, otherwise it is forwarded to terminal to be treated as SIGINT signal.

**Comment by stepanselyuk** [comment]
`Shift+Ctrl+C` and `Shift-Ctrl-V` are expected for the Linux terminal.

**Comment by dkapanidis** [comment]
For terminal yes, but since on all other sections of the UI (e.g. editor) the copy paste is done with Ctrl+C, Ctrl+V for uniformity it uses the same shortcuts.

btw, I tested it and while `Shift+Ctrl+C` does not work, `Shift+Ctrl+V` works as expected.

In future releases I may retake this to add support for `Shift+Ctrl+C` but since there is a working solution, it has now lower priority.

**Comment by stepanselyuk** [comment]
@dkapanidis I understand, just Linux users does not have a habit to use `Ctrl+C` to copy content in terminal, but rather it would add additional anxiety about what if that will stop running process in foreground in terminal.

**Comment by stepanselyuk** [comment]
On Linux such shortcut disabled by default, but can be enabled in settings, and people use `Ctrl+Short+A` for that. About `Ctrl+C` for copying on tty-enabled terminal, I would not :-) But for copying logs I rather find myself to use `Ctrl+C`, but having only `Ctrl+Short+C` is fine there.
