### ISSUE TITLE
Search field is cleared when switching between resources

### ISSUE THREAD

**Issue by GCh-OW** [harbur/kubernetic#181]
It was convenient when in search, the text was not cleared when switching between resources.
Version 2.9.1

**Comment by dkapanidis** [comment]
search filter is now upgraded to include more use-cases, to be released on `v2.12.0`:

* multiple filters can be added with *OR* logic, grouping view of resources.
* filters are done by `metadata.name` or `metadata.labels[]`. Labels are added as dropdown option for better discovery.
* can be typed without <enter> so that they only filter current screen.
* can be typed with <enter> to persist across screens.

![search](https://user-images.githubusercontent.com/367397/91843412-fed57a00-ec55-11ea-930f-879bff44dc5b.gif)

feedback is more than welcome of course if your use-case is not covered.
