### ISSUE TITLE
Pod Metrics

### ISSUE THREAD

**Issue by joshdcollins** [harbur/kubernetic#263]
In 3.0.0 I no longer see pod resource metrics (CPU/memory) in the Pod view -- has the criteria changed to display these?

**Comment by dkapanidis** [comment]
That was one (i think the only one) feature that didn't make it to the cut of 3.0.0 due to the table redesign.

It will be restored on next release, probably two new columns (CPU/Memory) with metrics per row, and potentially a mini-bar that makes a visual comparison between them.

Just for clarification, you refer to the metrics on the STATUS column, not the metrics graph on the top, which should appear in the new version.

version 2.13.0:
<img width="1440" alt="metrics" src="https://user-images.githubusercontent.com/367397/98735245-5ead7700-23a3-11eb-827b-f01223b040fd.png">

version 3.0.0:
<img width="1280" alt="Screenshot 2020-11-10 at 22 38 32" src="https://user-images.githubusercontent.com/367397/98736716-7c7bdb80-23a5-11eb-8ad8-09825b84d9c2.png">

Another issue I just saw is that the metrics graph on top does not appear until you first visit the Contexts View where the addons are listed.

The top graph will probably be shrinked as it takes too much screen, any feedback is welcome for improvement of course.

**Comment by joshdcollins** [comment]
Hi, yes - I did mean the values that were previously in the status column.

I have not yet seen the metrics graph.  When I click the Contexts view (I assume you mean from the profile menu) I just get the list of contexts from my kubeconfig with no mention of addons, etc.

**Comment by dkapanidis** [comment]
This is not a well advertised feature yet, probably will migrate to a separate section soon:

Click on the Context name and a list of enabled addons for context will appear. There you can enable/disable addons for that context. The two first addons are for metrics:
- The 1st one you probably already have it in place, since you could previously see metrics on the STATUS column.
- The 2nd one is the one that enables the metrics graph (a histogram of the metrics during last mins).
- The 3rd one is for OLM installation.


<img width="1096" alt="Screenshot 2020-11-11 at 10 21 24" src="https://user-images.githubusercontent.com/367397/98793080-ab2a9e00-2407-11eb-90d0-27c0ddca5ed0.png">

**Comment by dkapanidis** [comment]
Added table columns *CPU* and *Memory* which displays the current usage consumption of each resource.

In case of Nodes it displays the CPU and Memory consumption of each node and the % against the node capacity:

<img width="1101" alt="Screenshot 2020-11-16 at 17 43 28" src="https://user-images.githubusercontent.com/367397/99281881-50dc7380-2833-11eb-99b7-b32d8a00cb65.png">

In case of Pods it displays the CPU and Memory consumption of each pod and the % against the pod limits (sum of all containers):

<img width="1103" alt="Screenshot 2020-11-16 at 17 51 22" src="https://user-images.githubusercontent.com/367397/99282746-61d9b480-2834-11eb-9641-c74d9d5c4b92.png">

In case of higher-level Workloads (Deployments, DaemonSets, StatefulSets, Jobs) it displays the CPU and Memory consumption of the sum of their pods and the % against the their limits (sum of all pods):

<img width="1103" alt="Screenshot 2020-11-16 at 17 55 35" src="https://user-images.githubusercontent.com/367397/99283204-f7754400-2834-11eb-87d7-418f1a838166.png">

In case a workload doesn't have defined limits, no percentage will appear and the bar will be marked as grey (e.g. `nolimits`):

<img width="1100" alt="Screenshot 2020-11-16 at 17 57 22" src="https://user-images.githubusercontent.com/367397/99283481-5d61cb80-2835-11eb-9949-43bdb60cb96c.png">

For usage resources to be functional, metrics-server needs to be enabled on the cluster. An easy way to test your cluster if it has the ability is to use `kubectl`:

```
kubectl top pods
```

If there is no ability in your clusters, you can disable the metrics columns from the preferences:

<img width="878" alt="Screenshot 2020-11-16 at 18 01 14" src="https://user-images.githubusercontent.com/367397/99283764-bcbfdb80-2835-11eb-9e4e-1e9a2f26064a.png">

The table metrics are fetched periodically (every 5 secs) on the background.

Any feedback is welcome! It will be released on v3.1.0

**Comment by dkapanidis** [comment]
Also, columns are order-able so that you can for example quickly check the resources with higher consumption.
