### ISSUE TITLE
Deployment list not visible

### ISSUE THREAD

**Issue by niccoxx** [harbur/kubernetic#264]
Hi, when I try to open deployment's list I've a blank page and kubernetic doesn't work anymore. I've upgraded yesterday to 3.0.0 version.

**Comment by dkapanidis** [comment]
Hi,

can you provide some more information so that we can pinpoint the issue?

- Client OS:
- Kubernetes provider (AWS, GKE, baremetal?)
- Can you share a screenshot?
- Does this only happens on deployments list only, or all pages appear blank?
- Do you see the contexts on the top menu loaded ok? can you list contexts on the Contexts sections and connect to one? Is the connectivity icon green? (on the top menu)

**Comment by niccoxx** [comment]
Hi, I'm on Mac OS Catalina 10.15.4. I'm connecting on a baremetal infrastructure on 1.12 kubernetes version cluster.
It's happens only with deployments tab and all contexts are ready and with green icon.

**Comment by dkapanidis** [comment]
I suspect it has to do with the visualization of the deployment rows on your current namespace. Try to change namespace, or add a non-existent filter on the top-right search and see if the screen appears now empty, or with different deployments ok.

could you also share the output of a `kubectl` command (you can obfuscate the delicate parts as IP and data):

I'd like to see the API call for deployments (should be `apps/v1`, the request headers (should be `as=Table`) and the table itself:

```
$ kubectl get deployment --v=8
I1111 11:01:15.199727   50248 round_trippers.go:420] GET https://**********/apis/apps/v1/namespaces/tutorial/deployments?limit=500
I1111 11:01:15.199744   50248 round_trippers.go:427] Request Headers:
I1111 11:01:15.199750   50248 round_trippers.go:431]     Accept: application/json;as=Table;v=v1;g=meta.k8s.io,application/json;as=Table;v=v1beta1;g=meta.k8s.io,application/json
....
NAME       READY   UP-TO-DATE   AVAILABLE   AGE
backend    1/1     1            1           20h
frontend   1/1     1            1           20h
nginx      1/1     1            1           19h
```

**Comment by niccoxx** [comment]
I've no filter on a search tab for deployments, I should to watch only deployments in namespace.

This is the output of kubectl:

![screen_kubernetic](https://user-images.githubusercontent.com/45878511/98798741-84239a80-240e-11eb-8208-78228c087f94.png)

**Comment by dkapanidis** [comment]
I pinpointed it. There is an assumption that the containers is the 6th column, which was not always the case. I'll fix it by locating it properly and push a new version soon

```
❯ kubectl get deploy -o wide # v1.12.0
NAME   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES         SELECTOR
test   1         1         1            1           45s   test         nginx:alpine   app=test

❯ kubectl get deploy -o wide # v1.13.0
NAME       READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES         SELECTOR
nginx      1/1     1            1           20h   nginx        nginx:alpine   app=nginx
```

**Comment by niccoxx** [comment]
Thanks!

**Comment by dkapanidis** [comment]
The issue was a bit more complex than previously described:

Older kubernetes versions do not support `v1.Table` printer, instead your version supports `v1beta1.Table`, which manages to print but not stream in table format. Support for v1beta1.Table has been added on 3.0.1 release.

This means that for older kubernetes version there is no real-time streaming updates with custom tables (there is no way around this client-side). As a proof of this you can see that `kubectl` also does not support streaming of tables on older kubernetes versions:

```sh
❯ kubectl get pod --watch
NAME                    READY   STATUS    RESTARTS   AGE
test-777644f75c-5z6wj   1/1     Running   0          71m
test-777644f75c-72bvf   1/1     Running   0          135m
...
# open on a separate console and scale the deployment with `kubectl scale deployment test --replicas=3` to see changes
...
NAME                    AGE
test-777644f75c-5z6wj   72m
test-777644f75c-5z6wj   72m
```

Once the table is listed, updates are later received with generic columns (NAME, AGE).

Kubernetic 3.0.1 is being released with the ability to list resources, but for streaming ability you should upgrade your Kubernetes cluster to a newer version (<I'll update here with the exact kubernetes version>).
