### ISSUE TITLE
Implement support for multiple kubeconfig files

### ISSUE THREAD

**Issue by luispabon** [harbur/kubernetic#28]
When you're managing a large amount of different clusters, having all the configs on the same `~/.kube/config` file is cumbersome and prone to error, especially when cluster definitions change.

kubectl accepts an environment variable to switch config, `KUBECONFIG=/path/to/config`

It would be great if we could add hosts manually to kubernetic merely by showing it the relevant kubeconfig file, instead of being loaded only from `~/.kube/config`

**Comment by mikebryant** [comment]
It's also important to be able to merge multiple files, like kubectl does.
e.g. my `KUBECONFIG` variables is `/home/m/.kube/config:/home/m/git/kubernetes/overview-docs/files/kubeconfig`
(My personal settings, merged with a standard file the whole team shares via git)

**Comment by jakkaj** [comment]
It would be great if the app allowed you to open a config file manually also. The scenario is that I have a range of clusters set up in a range of files, and not all of them are present in my KUBECONFIG path.

**Comment by kaybinwong** [comment]
+1 @jakkaj

**Comment by mozai** [comment]
```
$ kubectl config get-contexts
CURRENT  NAME                          CLUSTER                       AUTHINFO
         asteroid                      asteroid                      ubuntu                           
         beta00.k8s.local              beta00.k8s.local              beta00.k8s.local                         
         beta01.k8s.local              beta01.k8s.local              beta01.k8s.local                         
         beta02.k8s.local              beta02.k8s.local              beta02.k8s.local                         
         beta03.k8s.local              beta03.k8s.local              beta03.k8s.local                         
*        alpha-ca-central-1.k8s.local  alpha-ca-central-1.k8s.local  alpha.k8s.local                 
         beta-us-east-1.k8s.local      beta-us-east-1.k8s.local      beta01.k8s.local                     
         gold-us-east-1.k8s.local      gold-us-east-1.k8s.local      gold01.k8s.local                     
         gold01.k8s.local              gold01.k8s.local              gold01.k8s.local                         
         alpha.k8s.local               alpha.k8s.local               alpha.k8s.local             
```
... but Kubernetic doesn't show any of them, not even the one marked 'current'.

I have multiple clusters to support, each created by different parties.  Having to throw all of the clusters/configs/users into one file is inviting disaster since the clusters I must support will have different authentications with the same name (ie alpha in canada and alpha outside canada both named their user auth "alpha.k8s.local", so putting both into the same ~/.kube/config will clobber one or the other).

I could swap the file on disk every time I want to start kubernetic, but that also means I have to shut it down entirely if I need to quickly check something on another cluster, and I can't use this tool to compare two clusters.

**Comment by stringaro-leo** [comment]
UP pls

**Comment by dkapanidis** [comment]
On v2.5.0 version the KUBECONFIG can now be configured in Preferences section:

<img width="1107" alt="Screenshot 2020-03-02 at 21 44 05" src="https://user-images.githubusercontent.com/367397/75716216-09c34800-5ccf-11ea-9569-855342079273.png">

It supports multiple files, same way `kubectl` uses KUBECONFIG environment variable.

Also extra PATH can be defined in order to locate external auth binaries that may be referenced in your KUBECONFIG files.

**Comment by dkapanidis** [comment]
> It would be great if the app allowed you to open a config file manually also. The scenario is that I have a range of clusters set up in a range of files, and not all of them are present in my KUBECONFIG path.

@jakkaj does the current solution covers your use case? you can have your extra files declared inside Kubernetic KUBECONFIG, leaving intact your CLI KUBECONFIG variable and still be able to operate them inside the App.
