### ISSUE TITLE
The activate button is not enabled when I put the license

### ISSUE THREAD

**Issue by warrenxxx** [harbur/kubernetic#286]
I just bought a license, and when copying and pasting the license in the text area, the activate button is not enabled so I cannot use kubernetic

**Comment by dkapanidis** [comment]
hi,
normally issues of licencing are due to one of the following reasons:
* make sure the last two characters  (`==`) are also included in the copy/paste of the license code.
* some email clients are splitting the license code with spaces. Remove the spaces before copy/pasting the code in the box.

waiting for feedback if it is resolved on your side, if not please sent an email at contact@harbur.io from your email used for the licence and we can regenerate one for you.

**Comment by igorkba** [comment]
I have the same problem.

**Comment by dkapanidis** [comment]
closing, if the issue persists please reopen with more details
