### ISSUE TITLE
Doesn't function if kubectl get ns and --all-namespaces aren't allowed

### ISSUE THREAD

**Issue by GJKrupa** [harbur/kubernetic#31]
Working in a secured environment where users are granted access to specific namespaces rather than having full admin access doesn't work - no data at all is displayed.  It would be very useful in such circumstances to be able to specify a list of known namespaces instead of relying on the API to interrogate this data.

**Comment by spiddy** [comment]
Hi,

probably the issue here is not being able to authenticate properly. RBAC-enabled environments are not yet tested, it is in the backlog at the moment.

What does the API return for namespaces (by `kubectl get namespaces -o yaml`), is it a complete list or a reduced view (I suspect the first from what you say). And how would you foresee the list of known namespaces be populated?

I would expect Kubernetes itself to be able to provide the information. Maybe we can ask the RBAC list, if the user has privileges for that namespace.

**Comment by spiddy** [comment]
ok, I just noticed the title, if the list of namespaces is not accessible by RBAC, then the namespace could be added in the `.kubecfg` and it can be picked up automatically (currently it doesn't pick it yet). Would that solve your use-case? For multiple namespace, multiple contexts can be defined in .kubecfg and switch between them.

**Comment by GJKrupa** [comment]
That would suit me perfectly.  That's how I define my contexts anyway to avoid having to add the -n flag every time I run kubectl.

**Comment by spiddy** [comment]
New version of Kubernetic (v2.0.13) now supports RBAC connection. The only necessary privilege is to be able to `watch` for the resources.

As for the namespace, now the context's namespace is respected, and shown on the namespace dropdown even if privileges cannot allow to view it resolving the issue.

Also added compatibility with `kubectx` and `kubens` cli commands (https://github.com/ahmetb/kubectx). Kube config is monitored for changes and when context or namespace is changed Kubernetic switches to the new environment.

**Comment by GJKrupa** [comment]
Works like a charm.  Thanks very much.
