### ISSUE TITLE
Activation Code Not Accepted

### ISSUE THREAD

**Issue by DarveyLavender** [harbur/kubernetic#330]
I received and entered the activation code on Linux and MacOS but the entering of the code did not change the Buy or Continue with Trial.

**Comment by dkapanidis** [comment]
Hi

Normally reports of invalid licenses are due to the following potential cases:
- Keys are finished with two "==" characters, make sure when copying the text they are also included.
- Some mail clients have been reported to split license keys with end-of-line. Make sure there are no empty lines between characters.
- In a weird situation a mail client added a "!" character in the license keys. The license keys are base64 of the signed license. They do not include characters such as "!". You can test the keys from your side by doing "echo $LICENSE_KEY  | base64 -D".


Hope this helps, please confirm if everything is ok here.

**Comment by DarveyLavender** [comment]
Thanks for the quick response. Noting that the license ended in == helped. I use Outlook and the in the email was truncated. I had to open the email in a browser.

You may close this case.

Darvey

________________________________
