### ISSUE TITLE
Your Activation code has expired.

### ISSUE THREAD

**Issue by markush81** [harbur/kubernetic#346]
Also, i bought a license (2020-02-26) with "unlimited app updates", i get 

>  Your Activation code has expired.  To renew your license click on "Buy License" button below.

checkout https://web.archive.org/web/20200414140642/https://kubernetic.com/

![Screenshot 2022-03-26 at 08 13 52](https://user-images.githubusercontent.com/3304672/160638190-f3f41ab2-834c-4d6c-97f0-bf8004d39da3.png)

**Comment by owenashurst** [comment]
Same issue here

**Comment by markush81** [comment]
And just to be clear https://github.com/harbur/kubernetic/issues/337 is referring to 2020-10 where it changed to 1-year update.

Customers before have "unlimited app updates", that's what we paid for.

**Comment by karcaw** [comment]
Same Issue Here

**Comment by dkapanidis** [comment]
Hi,

The license change has been explained in the blog post [here](https://www.kubernetic.com/blog/release-3-3-0). Bear in mind that this change is done in order to promote a more sustainable app development.

You can still use the app with the existing license up to version 3.2.0 without issues, for further updates from 3.3.0 onwards you need to purchase a new license.

Regarding the Kubernetic licensing, the one-time fee applied for Kubernetic 2 which was released until Oct 2020. For Kubernetic 3 (since 20 Oct 2020) the one-year of app updates apply. All licenses of Kubernetic 2 have been extended to Kubernetic 3 without limitations.

Since Kubernetic 3.3.0 the license has changed from perpetual to subscription and the app is now validating the already existing one-year of app updates limitation. These releases are a preparation for Kubernetic 4 which will be out soon.

For existing users a 20% discount was available for existing users until 31 of March for any number of licenses.

A further one-time 50% discount specifically for Kubernetic 2 users (purchased before 20 Oct 2020) is available until 31 of April, simply send an email at [contact@harbur.io](mailto:contact@harbur.io?subject=Discount50%) with your license and you will be granted the discount.

**Comment by karcaw** [comment]
Ok, I've moved back to 3.2.0 now.  Is there a way to turn off the Update Checker?  I don't need it asking me to upgrade.

**Comment by AlexandreCassagne** [comment]
Hi @dkapanidis, 

> Customers before have "unlimited app updates" even emphasised by "one time fee", that's what we paid for.

Your reply seems to imply you will not be honouring this. It is great that you are trying to make your business sustainable, but please honour the contract that we have agreed at the time. If not, please issue a refund. Thanks!

**Comment by AlexandreCassagne** [comment]
It seems you are refusing to honour the contract that we have signed in 2020 - I can see I am not the only user for whom this is the case.

This policy change is simply not acceptable - at the time, when Kubernetic was not a "mature" piece of software and I (and other early birds) bought it, it was exactly that--the promise of unlimited application updates.

You decided to change your business model--good for you! But you cannot remove "unlimited app updates", that is theft. 

I hope you reconsider your decision, because this is nothing other than **theft**. Thank you!

**Comment by AlexandreCassagne** [comment]
<img width="489" alt="Screenshot 2023-01-10 at 14 02 42" src="https://user-images.githubusercontent.com/541043/211639205-e9037360-3b07-4d36-bd14-b4cc185ac16c.png">

Kind reminder.

**Comment by dknoodle** [comment]
@dkapanidis I want to add my extreme objections to this as well. I have been using Kubernetic since it was initially released and I and other collages have purchased licenses with the understanding that they were perpetual. Today I tried to open Kubernetic and was met with a message saying my license key has expired, which is absolutely not what we originally paid for and supported.
