### ISSUE TITLE
3.4.0 release on windows not displaying any cluster resources

### ISSUE THREAD

**Issue by billpieper** [harbur/kubernetic#347]
Kubernetic 3.3.0 was working fine -- after updating to 3.4.0 app not seeing any cluster resources

Our Kubernetes clusters are Azure Kubernetes Service (AKS) and are running version 1.22.6

**Comment by billpieper** [comment]
Rolling back to 3.3.0 has fixed the issue for now.

**Comment by m-fitzgerald** [comment]
I am also experiencing this issue. Forgive the newbie question but where can I find a v3.3 download for Windows? Do I have to build it myself?

**Comment by dkapanidis** [comment]
The links for the previous version (3.3.0) are [Mac](https://kubernetic.s3.amazonaws.com/Kubernetic-3.3.0.dmg), [Linux](https://kubernetic.s3.amazonaws.com/Kubernetic-3.3.0.AppImage), [Win](https://kubernetic.s3.amazonaws.com/Kubernetic+Setup+3.3.0.exe).

As soon as a fix is available I will notify here so that you can upgrade properly.

**Comment by mrjamiebowman** [comment]
Sure! Hope this helps.

OS: Windows 10
Kubernetes version: 1.19.9
Kubernetes cloud provider: Azure
Custom KUBECONFIG path: I don't think so
Authentication tooling binary: I use Azure CLI to authenticate..? (Checked I am authed)

**Comment by dkapanidis** [comment]
fixed on `v3.4.1`.

This is a hotfix release just for windows in order to solve this issue (other OS variants are not released as they are not affected)

The issue was due to update on the `react-router-dom` to v6 and affected only Windows release.

More specifically the [BrowserRouter](https://reactrouter.com/docs/en/v6/getting-started/overview) was used until now, which is now changed to [HashRouter](https://reactrouter.com/docs/en/v6/api#setup).

The difference between the two is that BrowserRouter uses the URL to do navigation e.g. `file:///resources/deployments/` and HashRouter uses the `hash` portion of the current URL e.g. `file:///app_location/#/resources/deployments/`.

The first one was working properly until now on all environments but with latest dependency update it stopped working on Windows because the URL was now rendered including the drive e.g. `file:///C:/resources/deployments/` breaking the rendering.

For desktop environment using electron the HashRouter is a better choice to avoid edge-cases as the above.

The change will also be rolled on the other OS variants from next release.
