### ISSUE TITLE
Sorting by time/ages sorts lexigraphically 

### ISSUE THREAD

**Issue by pinkfloydx33** [harbur/kubernetic#360]
Sorting by time/age (for example on the events screen) does not sort by the amount of time, but rather by the characters that make up the text. For example, sorting ascending will produce:

- 1s
- 2min
- 30s
- 4days
- 5s

But this should obviously sort as:
- 1s
- 5s
- 30s
- 2min
- 4days

**Comment by dkapanidis** [comment]
Resolved for next release `4.2.0`

Related to #285, #265, #22.

The relative formatted text is coming as is from Kubernetes API, in order to format them properly they are converted to secs internally, while the presentation is kept as is.

There are multiple columns that are using the _age_ format:

* Age (most Resources)
* Last Seen, First Seen (Events)
* Duration (Jobs)
* Last Schedule (CronJobs)

Also there are CRDs that contain `type: 'date'` in their columnDefinitions, e.g:
* Start Time (Tekton TaskRuns & PipelineRuns)
* Completion Time (Tekton TaskRuns & PipelineRuns)

All of those examples are now sortable properly instead of alphabetically.
