### ISSUE TITLE
I bought the license before, why can't the license be used after the update from 3.2 to V4.1? 

### ISSUE THREAD

**Issue by daniel-vv** [harbur/kubernetic#363]
I bought the license before, why can't the license be used after the update from 3.2 to V4.1?

**Comment by tomaszym** [comment]
Just to make it clear... Was that `one time fee` AND `unlimited app updates` license? :popcorn:

**Comment by dkapanidis** [comment]
Hi,

The license change has been explained in the blog post [here](https://www.kubernetic.com/blog/release-3-3-0). Bear in mind that this change is done in order to promote a more sustainable app development.

You can still use the app with the existing license up to version 3.2.0 without issues, for further updates from 3.3.0 onwards you need to purchase a new license.

Regarding the Kubernetic licensing, the one-time fee applied for Kubernetic 2 which was released until Oct 2020. For Kubernetic 3 (since 20 Oct 2020) the one-year of app updates apply. All licenses of Kubernetic 2 have been extended to Kubernetic 3 without limitations.

Since Kubernetic 3.3.0 the license has changed from perpetual to subscription and the app is now validating the already existing one-year of app updates limitation. These releases are a preparation for Kubernetic 4 which was released soon after.
