### ISSUE TITLE
Events section

### ISSUE THREAD

**Issue by david-espinosa** [harbur/kubernetic#50]
In the latest version, the Events section has disappeared. 
IMO it was one of the key features of this app, the one that made move from k8s's proxy.
I would like to ask you to include it again.
Thanks.

**Comment by spiddy** [comment]
The events section was removed to reduce traffic on watch events since it was very noisy on traffic.

It will be re-introduced in two steps:

- Each resource will have an events tab to be able to see the events related to that resource
- A list of resources will be added to be optionally watched on the settings section. This list will be retrieved by the Kubernetes API, in order to support watching CRD resources.

but since it is a missed feature it will also be added as it was, and it will be moved as optional when the option to watch a custom list is added.

let's keep this issue for reintroducing the events section back as it was, the other steps will be added as separate issues.

**Comment by david-espinosa** [comment]
Cool! Thanks for taking back this awesome feature!

**Comment by duusty** [comment]
Are there any news regarding the events section ? 
Iam currently using the latest version in trial mode and could not find it. 

Thanks!

**Comment by dkapanidis** [comment]
added on the backlog for next release

**Comment by dkapanidis** [comment]
Done, will be released on v2.8.0.

All resources (global and namespaced) now have an events tab where you can see related events:

<img width="1279" alt="Screenshot 2020-05-21 at 14 05 56" src="https://user-images.githubusercontent.com/367397/82557546-3703f180-9b6c-11ea-9056-f62a73fc67f9.png">
