### ISSUE TITLE
Not supporting KUBECONFIG, error from missing config file

### ISSUE THREAD

**Issue by jnardiello** [harbur/kubernetic#56]
I think Kubernetic is cool and is a much needed decent client-side dashboard for your clusters. That being said, the current implementation is quite limited (I do realise this is an early version). 

Currently Kubernetic works only using `.kube/config`, which for complex scenarios is not the case. Being able to work with multiple clusters is critical for this tool to be useful therefore I think it should support `KUBECONFIG` as well.

Currently, if `config` file is missing, client is throwing this error
<img width="521" alt="screen shot 2018-06-14 at 05 50 11" src="https://user-images.githubusercontent.com/657293/41390745-46dcbe00-6f97-11e8-8669-826fae208dd7.png">

**Comment by senorequeso** [comment]
Just a little additional details on this issue:

If you have multiple clusters with multiple config files, you can set `KUBECONFIG` to be a colon-separated list of config files (.e.g. `export KUBECONFIG=/path/to/config1:/path/to/config`. This also allows you to store your kubernetes config file in a non-default location and still use `kubectl` tools with it. It'd be very awesome if kubernetic supported it.

**Comment by spiddy** [comment]
One of the problems to add support for KUBECONFIG it is difficult to automatically pick up user's env variables, depending where they setup the KUBECONFIG variable. Kubernetic can be launched outside of shell and it may not have the same variables loaded. 

Instead of automatically picking up the variable we can add support to configure it inside the app, and storing the settings locally (probably under `~.kubernetic/` folder)

As an alternative until then you can merge locally the KUBECONFIG files using `kubectl config view`

**Comment by mumrau** [comment]
I would add that the complete command to go from an ENV variable based setup to a kubernetic ready setup would be `kubectl config view --raw > ~/.kube/config`.

Nonetheless, I believe this feature should be implemented, cause I do believe in most of kubernetes administrators installations, the variables would be shared with the kubernetic process, or we'll find a way to ensure so.

**Comment by jurgenweber** [comment]
eta on this feature?

**Comment by dkapanidis** [comment]
On v2.5.0 version the KUBECONFIG can now be configured in Preferences section:

<img width="1107" alt="Screenshot 2020-03-02 at 21 44 05" src="https://user-images.githubusercontent.com/367397/75716216-09c34800-5ccf-11ea-9569-855342079273.png">

It supports multiple files, same way `kubectl` uses KUBECONFIG environment variable.

Also extra PATH can be defined in order to locate external auth binaries that may be referenced in your KUBECONFIG files.
