### ISSUE TITLE
Proposal: Additional Column Info 

### ISSUE THREAD

**Issue by vrubiella** [harbur/kubernetic#69]
Will be so useful view image tag info were pods/deployments are listed.

And, ¿what about custom columns?. filling a field with go templates adding customizable columns.

**Comment by spiddy** [comment]
Hi,

Deployments (and other Controllers) already have that info under the _STATUS_ column, though you're right in the pods there is no such info currently, due to lack of space.

![screen shot 2018-09-27 at 11 38 38](https://user-images.githubusercontent.com/367397/46137438-e9759b00-c249-11e8-88ac-d8a7df96f1a9.png)

Back to the Pods view:

Maybe the current status (ContainerCreating/Running/Terminating/Backoff) can be visualized by the _READY_ column color theme with details on hover, so that we can add image tag on the _STATUS_ column.

Also the _STATUS_ column shows the number of restarts, that probably should stay on the _STATUS_ column.

**Comment by dkapanidis** [comment]
Dynamic tables with customizable columns Implemented on `v3.0.0`

Each resource type displays resource-specific columns as shown in `kubectl`, supporting also CRDs. It displays by default the columns shown using kubectl with the option to display extra columns (that can be enabled in CLI with `kubectl -o wide`).

<img width="1104" alt="Screenshot 2020-11-10 at 14 27 38" src="https://user-images.githubusercontent.com/367397/98679905-f342b580-2360-11eb-98a7-5d2443c83395.png">

<img width="1106" alt="Screenshot 2020-11-10 at 14 28 25" src="https://user-images.githubusercontent.com/367397/98679958-05bcef00-2361-11eb-8a9f-d6bb6921b73f.png">
