### ISSUE TITLE
Not comfortable logs

### ISSUE THREAD

**Issue by highfeed** [harbur/kubernetic#80]
I want to auto-scroll and colors in logs of pods.

![image](https://user-images.githubusercontent.com/8414117/52518376-c842a380-2c5a-11e9-9699-117a9a4aed9c.png)

**Comment by capsalad** [comment]
Yes, it would be nice if Kubernetic was able to support [ANSI escape sequences](https://en.wikipedia.org/wiki/ANSI_escape_code).

**Comment by lsorba** [comment]
Agreed, it would be nice!

**Comment by marcopala81** [comment]
Also, in the new 3.0.0 release, the logs font is not monospaced anymore (it was prior to the update). It's quite "messy" to read now:

![image](https://user-images.githubusercontent.com/22928074/98799785-79b1d280-2407-11eb-96d9-b1918ce4ef28.png)

It would be nice having some kind of "font style preferences" options (style/size), or at least revert it the logs font back to monospaced.

Thanks,
M

**Comment by dkapanidis** [comment]
font logs to be reverted in monospace is fixed here #261

**Comment by marcopala81** [comment]
Just got the update, @dkapanidis ! Everything back to normal:

![image](https://user-images.githubusercontent.com/22928074/98958845-a0046a80-24fa-11eb-87e6-09b59ca7b2a4.png)

Thanks for the quick intervention! :+1:

**Comment by dominch** [comment]
Still no ANSI codes inside :(

**Comment by dkapanidis** [comment]
Logs have been revamped!

The Logs are now using xtermJS canvas same as Terminal which is a lot more performant than HTML DOM changes as was before.

Due to this restriction there was a default limit of showing only x number of lines, which is now lifted and by default you can see the last 48h (which is configurable and persistent across app restarts)

Also the logs are now streamed in binary format instead of string which enables ANSI colors :)

![Screenshot 2022-06-28 at 17 28 05](https://user-images.githubusercontent.com/367397/176219207-a96ade77-9ce4-4889-9fcc-b0254020945b.png)
